apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: leastconn
    haproxy.router.openshift.io/disable_cookies: "true"
    openshift.io/host.generated: "true"
  labels:
    app: lb-deployment
    app.kubernetes.io/component: lb-deployment
    app.kubernetes.io/instance: lb-deployment
    app.kubernetes.io/part-of: Demo
    app.openshift.io/runtime-version: latest
  name: lb-deployment
spec:
  host: lb-deployment-lb-demo.apps-crc.testing
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: lb-deployment
    weight: 100
  wildcardPolicy: None
